version: '3.7'
services:

  sigma_magento-nginx:
#    image: nginx:1.21.6-alpine
# amatkovskiy/sigma_magento-nginx:1.21.6
    container_name: sigma_magento-nginx
    volumes:
      - ./magento2:/var/www/html
    build:
      context: ./nginx/
    ports:
      - 8081:80
    restart: always
    environment:
      - PHP_FPM_HOST=sigma_magento-php_fpm
      - PHP_FPM_PORT=9000
    # depends_on:
    #   - sigma_magento-php_fpm
#    networks:
#      - network
 
  sigma_magento-php_fpm:
    build:
      context: ./php-fpm/
    container_name: sigma_magento-php_fpm
    volumes:
      - ./magento2:/var/www/html
    restart: always
    # depends_on:
    #   - sigma_magento-data
#    networks:
#      - network

  sigma_magento_db:
    image: mysql:8.0-debian
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    container_name: sigma_magento_db
    environment:
      MYSQL_DATABASE: 'local_magento_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'local_agent'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'local_password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root_strong_password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
#    networks:
#      - network



  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  sigma_magento_elasticsearch:
    image: elasticsearch:7.16.3
    container_name: sigma_magento_elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
#    networks:
#      - network

#  sigma_magento_kibana:
#    container_name: sigma_magento_kibana
#    image: docker.elastic.co/kibana/kibana:7.17.0
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    ports:
#      - 5601:5601
#    depends_on:
#      - elasticsearch

# Names our volume
volumes:
  my-db:
  elasticsearch-data:
    driver: local

#networks:
#  network:
#    driver: bridge
