name: Create and push php-fpm image to ECR

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Test scan'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - create php image
      tags:
        description: 'skip scan'
        required: false 
        type: boolean

env:
  AWS_REGION:           eu-central-1
  TAG_PHP:              latest
  ECR_REPOSITORY_PHP:   php-fpm
  ECR_REGISTRY_PHP:     908410081654.dkr.ecr.eu-central-1.amazonaws.com
  SKIP_SCAN:            ${{ github.event.inputs.tags }}    
  
jobs:
  deploy:
    name: Deploy ubuntu
    runs-on: ubuntu-latest
    permissions:
      packages: write
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
          
    - name: build php image           
      run: 
        docker build -f php-fpm/Dockerfile -t $ECR_REGISTRY_PHP/$ECR_REPOSITORY_PHP:$TAG_PHP . 
        
    - name: scan php image
      if: ${{ env.SKIP_SCAN == 'false' }}
      uses: anchore/scan-action@v3.2.5
      continue-on-error: true
      with:
        image:  908410081654.dkr.ecr.eu-central-1.amazonaws.com/php-fpm:latest
        fail-build: false
        severity-cutoff:  High
        
    - name: push php image
      run: 
        docker push $ECR_REGISTRY_PHP/$ECR_REPOSITORY_PHP:$TAG_PHP


      
