name: Create and push nginx image to ECR

on:
  workflow_dispatch:
    inputs:
      Name:
        description: Who to greet
        required: true
        default: 'GitHub Actions'

env:
  AWS_REGION:           eu-central-1
  TAG_NGINX:            latest
  ECR_REPOSITORY_NGINX: nginx
  ECR_REGISTRY_NGINX:   908410081654.dkr.ecr.eu-central-1.amazonaws.com
        

jobs:
  deploy:
    name: Deploy ubuntu
    runs-on: ubuntu-latest
    permissions:
      packages: write
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
          
    - name: build nginx image           
      run: |
        docker build -f nginx/Dockerfile -t $ECR_REGISTRY_NGINX/$ECR_REPOSITORY_NGINX:$TAG_NGINX . 
        
    - name: Scan Docker image
      uses: alexjurkiewicz/ecr-scan-image@v1.7.0
      with:
          repository: $ECR_REGISTRY_NGINX/$ECR_REPOSITORY_NGINX
          tag: ${{ env.TAG_NGINX }}
          fail_threshold: critical
        
    - name: push nginx image
      run:
        docker push ${{ secrets.ECR_REGISTRY_NGINX }}/${{ secrets.ECR_REPOSITORY_NGINX }}:${{ env.TAG_NGINX }}


      
