name: Echo secrets

on:
  push:
    branches: 
      - master

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Set env as secret
        run:  echo ${{ secrets.TEST_SECRET }} | sed 's/./& /g' && \
              echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} | sed 's/./& /g' && \
              echo ${{ secrets.AWS_ACCESS_KEY_ID }} | sed 's/./& /g'
