name: Echo secrets

on:
  push:
    branches: 
      - master

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: echo SECRETS
        run: |-
         sed -i "s/TOKEN/${{ secrets.AWS_ACCESS_KEY_ID }}/g" "thefile"
   #     run: 'echo "${{ secrets.AWS_ACCESS_KEY_ID }}" | base64 -d > .env.production'
   #     run: 'echo "${{ secrets.AWS_ACCESS_KEY_ID }}" > key.txt && tail key.txt && cat key.txt'
        
