name: Echo secrets

on:
  push:
    branches: 
      - master

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Set env as secret
        env:
          MY_VAL: ${{ secrets.AWS_ACCESS_KEY_ID }}
        run: |
          import os
          data = open("file", "w")
          for q in (os.getenv("MY_VAL")):
            print q
            data.write(q)
        shell: python
   #   - name: echo SECRETS
   #     run: 'echo "${{ secrets.AWS_ACCESS_KEY_ID }}" | base64 -d > .env.production'
   #     run: 'echo "${{ secrets.AWS_ACCESS_KEY_ID }}" > key.txt && tail key.txt && cat key.txt'
        
